name: Production-Imaging-macOS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: Aspose/products.aspose.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true
    - name: Install autoprefixer
      run:  npm install -D --save autoprefixer
    - name: Install postcss-cli
      run:  npm install -D --save postcss-cli
    - name: Find and replace domain name
      run: find . -type f -name '*.md' -exec sed -i '' s/products.aspose.com/products-qa.aspose.com/g {} +
    - name: Build Imaging
      run: hugo --config "./config-prod.toml" -c "content/imaging" -b "https://products.aspose.com/imaging" --cleanDestinationDir --minify
    - name: Deploy Imaging to S3
      run: hugo deploy --config "./config-prod.toml" --maxDeletes=-1 --target "imaging" --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
