name: Diagram-Production

on:
  repository_dispatch:
    types: [production-complete]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: Aspose/products.aspose.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true
    - name: Install autoprefixer
      run:  npm install -D --save autoprefixer
    - name: Install postcss-cli
      run:  npm install -D --save postcss-cli
    - name: Find and replace url param in frontmatter
      run: find . -type f -name '*.md' -exec sed -i '' s/url:/url_ignore:/g {} +
    - name: Build Diagram
      run: hugo --config "configs/diagram.toml" -c "content/diagram" -b "https://products.aspose.com/diagram" --cleanDestinationDir --minify
    - name: Deploy Diagram to S3
      run: hugo deploy --config "configs/diagram.toml" --maxDeletes=-1 --target "production" --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
