name: Imaging-Staging

on:
  repository_dispatch:
    types: [staging-complete]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-13
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: Aspose/products.aspose.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          ref: samer.el-khatib.IMAGINGNET-7399_2_with_content
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'
          extended: true
    - name: Install autoprefixer
      run:  npm install -D --save autoprefixer
    - name: Install postcss-cli
      run:  npm install -D --save postcss-cli    
    - name: Find and replace domain name
      run: LC_ALL=C find . -type f -name '*.md' -exec sed -i '' s/products.aspose.com/products-qa.aspose.com/g {} +
    - name: Build Imaging
      run: hugo --config "./configs/imaging.toml" -c "content/imaging" -b "https://products-qa.aspose.com/imaging" --cleanDestinationDir --minify
    - name: Deploy Imaging to S3
      run: hugo deploy --config "./configs/imaging.toml" --maxDeletes=-1 --target "staging" --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
