name: 01-Staging-Complete

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Dispatch Events
      uses: peter-evans/repository-dispatch@v1
      with:
          token:  ${{ secrets.REPO_TOKEN }}
          event-type: staging-complete