name: Home-Staging

on:
  repository_dispatch:
    types: [staging-complete]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: Aspose/products.aspose.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true
    - name: Install autoprefixer
      run:  npm install -D --save autoprefixer
    - name: Install postcss-cli
      run:  npm install -D --save postcss-cli
    - name: Find and replace url param in frontmatter
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "url:"
        replace: "url_ignore:"
        include: "_index.md"
    - name: Find and replace domain name
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "products.aspose.com"
        replace: "products-qa.aspose.com"
        include: "_index.md"
    - name: Find and replace image url domain
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "logoImageSrc=\"https://www.aspose.cloud/"
        replace: "logoImageSrc=\"https://cms.admin.containerize.com/"
        include: "_index.md"
        
    - name: Build Home
      run: hugo --config "configs/home.toml" -b "https://products-qa.aspose.com" --cleanDestinationDir --minify

    - name: Upload default language
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products-qa.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/'
        DEST_DIR: '/' 
        
    - name: Upload en sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.aspose.com'
        file_path: 'public/en/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'en'
