name: TeX-Staging

on:
  repository_dispatch:
    types: [staging-complete]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: Aspose/products.aspose.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true
    - name: Install autoprefixer
      run:  npm install -D --save autoprefixer
    - name: Install postcss-cli
      run:  npm install -D --save postcss-cli
    - name: Find and replace url param in frontmatter
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "url:"
        replace: "url_ignore:"
        include: "_index.md"
    - name: Find and replace domain name
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "products.aspose.com"
        replace: "products-qa.aspose.com"
        include: "_index.md"
    - name: Find and replace image url domain
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "logoImageSrc=\"https://www.aspose.cloud/"
        replace: "logoImageSrc=\"https://cms.admin.containerize.com/"
        include: "_index.md"
    - name: Build TeX
      run: hugo --config "./config.toml" -c "content/tex" -b "https://products-qa.aspose.com/tex" --cleanDestinationDir --minify
    - name: Deploy TeX to S3
      run: hugo deploy --config "./config.toml" --maxDeletes=-1 --target "tex" --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
