# This work will only work when there is a change in theme files.
name: Test_Checkout_other_Pvt_Repo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main1 ]
    paths:
      - 'themes/lutsk-aspose-theme/**'
  pull_request:
    branches: [ main1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    # Step 2 - Sets up the latest version of Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true

    # Step 3 - Clean and don't fail
#    - name: Clean public directory
#      run: rm -rf public

    # Step 4 - Builds the site using the latest version of Hugo
    # Also specifies the theme we want to use
    - name: Install Dependicies1
      run:  npm install -D --save autoprefixer

    - name: Install Dependicies2
      run:  npm install -D --save postcss-cli

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "url:"
        replace: "url_ignore:"
        include: "_index.md" # Will match all README.md files in any nested directory
    - name: Find and Replace domain name
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "products.aspose.com"
        replace: "products-qa.aspose.com"
        include: "_index.md" # Will match all README.md files in any nested directory

    - name: Find and Replace image url domain
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "logoImageSrc=\"https://www.aspose.cloud/"
        replace: "logoImageSrc=\"https://cms.admin.containerize.com/"
        include: "_index.md" # Will match all README.md files in any nested directory

    - name: Build 3d
      run: hugo --config "./config-i18n.toml" -c "content/3d" -b "https://products-qa.aspose.com/3d" --cleanDestinationDir --minify
