name: total-split
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Build environment
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      NODE_ENV: ${{ github.event.inputs.environment }}
      HUGO_ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        configure_one_product:
          - sharepoint
          - python-net
          - python-java
          - family

    steps:
      - name: Checkout theme repo
        uses: actions/checkout@main
        with:
          repository: Aspose/products.aspose.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.101.0
          extended: true
      - name: Install Node.js Dependencies
        run: npm install
      - name: Install autoprefixer
        run: npm install -D --save autoprefixer
      - name: Install postcss-cli
        run: npm install -D --save postcss-cli
      - name: Configure build environment
        env:
          CONFIGURE_ONE_PRODUCT: ${{ matrix.configure_one_product }}
        run: npm run configure
      - name: Display config.json
        run: cat /Users/runner/work/products.aspose.com-workflows/products.aspose.com-workflows/config.json
      - name: Build Total
        run: hugo --config "configs/total.toml","config.json" -c "content/total" -b "https://products-qa.aspose.com/total" --cleanDestinationDir --minify
          --templateMetrics --templateMetricsHints
      - name: Prepare public folder
        run: |
          for f in /Users/runner/work/products.aspose.com-workflows/products.aspose.com-workflows/public/**/sitemap.xml;
          do
            mv "$f" "${{ matrix.configure_one_product }}.xml"
          done  
        
      - name: Deploy Total to S3
        run: hugo deploy --config "configs/total.toml" --maxDeletes=0 --target "staging"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
